import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";
import FooterSection from "@/components/FooterSection";
import "./globals.css";

const dnSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dnSans.className} bg-brand-dark pb-28`}>
        <NavigationBar />
        <div className="w-full">{children}</div>
        <FooterSection />
      </body>
    </html>
  );
}
